language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script:
   - gradle --quiet --no-color --no-search-upward --info test

notifications:
  email: false
  hipchat:
    rooms:
      - c92bad93fc0d9c2d195d80c7be121a@Orchestrate
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}'
